# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.17.0/www/docs/static/schema.json
version: 2

project_name: protoss

builds:
  - id: protoss
    main: ./cmd/protoss
    binary: protoss
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X github.com/protossai/protoss-cli/internal/result.CLIVersion={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: protoss-archives
    ids:
      - protoss
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - THIRD_PARTY_NOTICES

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"

release:
  draft: true
  prerelease: auto
  name_template: "Protoss CLI {{ .Tag }}"
